---
name: Build, Scan & Push

# Make the workflow re-usable
on:
  workflow_call:
    inputs:
      image_tags:
        description: |
          The tags the pushed image will have.
          i.e. for pull requests : type=raw,value=PR-{{date 'YYYYMMDD'}}-{{sha}}
          You can enter multiple tags using a pipe
          Reference : https://github.com/docker/metadata-action#tags-input
        required: true
        type: string
      trivy_version:
        description: "Version of Trivy to use"
        default: "0.30.4"
        required: false
        type: string
      trivy_threshold:
        description: "Trivy scan threshold for failure (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)"
        default: "HIGH,CRITICAL"
        required: false
        type: string
      trivy_ignore_unfixed:
        description: "Ignore unfixed CVEs in Trivy scan"
        default: true
        required: false
        type: boolean
      trivy_full_scan:
        description: "Adds another Trivy scan without threshold"
        default: true
        required: false
        type: boolean

jobs:

  build-scan-push:

    name: Build, scan & push Dockerfile
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      packages: write
      security-events: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub CR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: ${{ inputs.image_tags }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Install Trivy
        run: |
          VERSION=${{ inputs.trivy_version }}
          curl -sSL -o ./trivy.tar.gz https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
          tar -xvf trivy.tar.gz
          mv trivy /usr/local/bin/trivy

      - name: Generate Trivy sarif report for fixable CVEs
        run: |

          trivy image ${{ steps.metadata.outputs.tags }} ${{ inputs.trivy_ignore_unfixed && '--ignore-unfixed' || '' }} --format sarif --vuln-type os,library --severity ${{ inputs.trivy_threshold }} --output trivy-results.sarif

      - name: Upload Trivy sarif report
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Full scan with Trivy
        if: ${{ inputs.trivy_full_scan }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.metadata.outputs.tags }}
          exit-code: 0
